# Generated by Django 3.2.8 on 2021-10-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brewerycategory',
            options={'verbose_name_plural': 'Brewery Category'},
        ),
        migrations.AlterModelOptions(
            name='countrycategory',
            options={'verbose_name_plural': 'Country Category'},
        ),
        migrations.AlterModelOptions(
            name='stylecategory',
            options={'verbose_name_plural': 'Style Category'},
        ),
        migrations.AddField(
            model_name='brewerycategory',
            name='brewery_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='abv',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True),
        ),
    ]
